// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkingApp.Data;

#nullable disable

namespace ParkinApp.Migrations
{
    [DbContext(typeof(ParkingDbContext))]
    partial class ParkingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("ParkingApp.Entities.ParkingSpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReservationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ParkingSpots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsReserved = false,
                            TimeZoneId = "UTC+1"
                        },
                        new
                        {
                            Id = 2,
                            IsReserved = false,
                            TimeZoneId = "UTC+1"
                        },
                        new
                        {
                            Id = 3,
                            IsReserved = false,
                            TimeZoneId = "UTC+1"
                        },
                        new
                        {
                            Id = 4,
                            IsReserved = false,
                            TimeZoneId = "UTC+1"
                        },
                        new
                        {
                            Id = 5,
                            IsReserved = false,
                            TimeZoneId = "UTC+1"
                        },
                        new
                        {
                            Id = 6,
                            IsReserved = false,
                            TimeZoneId = "UTC+1"
                        },
                        new
                        {
                            Id = 7,
                            IsReserved = false,
                            TimeZoneId = "UTC+1"
                        },
                        new
                        {
                            Id = 8,
                            IsReserved = false,
                            TimeZoneId = "UTC+1"
                        },
                        new
                        {
                            Id = 9,
                            IsReserved = false,
                            TimeZoneId = "UTC+1"
                        },
                        new
                        {
                            Id = 10,
                            IsReserved = false,
                            TimeZoneId = "UTC+1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
